eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
    oauth:
       issuer: https://dev-76594027-admin.okta.com/oauth2/default
       audience: api://default
      

